version: "3.7"
services:
  rethinkdb:
    restart: "always"
    image: rethinkdb:2.4.1
    ports:
      - "127.0.0.1:29015:29015"
      - "127.0.0.1:28015:28015"
      - "127.0.0.1:8080:8080"
    volumes:
      - ./rethinkdb:/data
